boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h x86_desc.h idt_handlers.h
idt_handlers.o: idt_handlers.c idt_handlers.h lib.h types.h x86_desc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h page.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h x86_desc.h types.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h idt.h page.h
